services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: s1lite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ../api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/s1lite
      - ALERT_CHANNEL=slack
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../api:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: ../web
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ../web:/app
      - /app/node_modules

volumes:
  postgres_data:
